# experiment params
"NUM_SEEDS": 1
"SEED": 0

# wandb params
"ENTITY": ""
"PROJECT": ""
"WANDB_MODE": "disabled"

# where to save the params (if None, will not save)
"SAVE_PATH": "baselines/QLearning/checkpoints"

hydra:
  sweeper:
    params:
      "SEED": 0,1,2,3,4,5
